### PR TITLE
Add arg passthrough to `go test`

### LINKED ISSUE #8: Support passing arguments to go test
We run our tests in CI with `-race -v`, it'd be nice if we could keep the same output, while still using overalls to actually run the tests per package and merge the coverage output.

Being able to pass arguments like `go list` takes would also be nice.

I'm happy to try and add this myself, but that would require a bit of bikeshedding (of test output, of arguments) so I wanted to bring this up for discussion first

### PR DESCRIPTION
**Pull request by ascandella**
Fixes #8 

I also added output for failure messages, which I can break into a separate PR but I think is useful if the tests fail.

### CODE REVIEW

**Comment by ascandella** [comment]
cc @prashantv we're using this in UberFx now, see recent commit on master to enable it. Pointed it at my fork until this PR gets merged but I'd like to use this project going forward instead of concatenating coverage files together.

**Comment by deankarn** [comment]
Thanks @sectioneight 

I was just looking at the changes and they look good to me, I'll merge them ASAP so you don't have to be dependant on a fork.

**Comment by ascandella** [comment]
Wow, that was quick!

For reference, here's how I'm using it in my project (this is in a Makefile hence the weird syntax)

``` bash
overalls.coverprofile:
  overalls -project=$(PROJECT_ROOT) \
    -ignore "$(OVERALLS_IGNORE)" \
    -covermode=atomic \
    $(DEBUG_FLAG) -- \
    $(TEST_FLAGS) $(RACE) $(TEST_VERBOSITY_FLAG)
  gocov convert $@ | gocov report
```

`$(DEBUG_FLAG)` is set to `-debug` if verbose mode is turned on. `$(RACE)` is set to `-race` in normal runs. `$(TEST_VERBOSTY_FLAG)` is set to `-v` in verbose runs

**Comment by deankarn** [comment]
Thanks @sectioneight nice to see how others are using it :thumbsup:

No problems, every project in go-playground I built based on a need and am using them in one or more Enterprise applications; and your pull request is also helping me :smile: love open source!

Besides who doesn't hate a pull request hanging out there!

**Comment by ascandella** [comment]
Nice to see somebody who responds to PR requests :) And as per this project, thanks for putting it together. In case you can't glean from my GH page, this tool is going to be used in some open source code for a company that starts with the letter "u" and rhymes with "tuber"

**Comment by deankarn** [comment]
I gathered, still awesome thought!

Well if you need anything else with this or any other project, just let me know; more than happy to help.

**Pull request merged**
